import Foundation
import AVFoundation
import SwiftUI
import Combine

// MARK: - Voice Service
//
// The spoken voice layer for the agent squad. Every agent announces
// what they're starting (open) and what they accomplished (close) at
// each heartbeat. Announcements are generated by the LLM as the first
// and last line of its response — AgentScheduler peels them off and
// routes them through this service.
//
// Design rules (from the architecture pass):
//   • One utterance speaks at a time. Concurrent announcements queue.
//   • Queue depth capped (default 3). Fourth announcement drops the oldest
//     — agents shouldn't stack up more than a few seconds of backlog.
//   • Global mute kills the queue instantly.
//   • Per-agent mute (on AgentSpec.voiceMuted) is respected at enqueue time.
//   • Quiet hours (default 22:00–07:00) silently drop announcements but
//     still log them to the flight recorder.
//   • Siri-2-ready: everything goes through AVSpeechSynthesizer, so when
//     Apple adds a .neural quality tier or new identifiers, flipping the
//     voiceIdentifier on an AgentSpec is the only change needed.
//
// Thread safety: @MainActor — all state mutations happen on the main
// thread. AVSpeechSynthesizer's delegate callbacks are marshaled back
// onto the main actor before touching state.

@MainActor
final class VoiceService: NSObject, ObservableObject {
    // MARK: Published state (UI bindings)

    /// Master mute. When true, all announcements are dropped on enqueue.
    @Published var muted: Bool = false {
        didSet {
            if muted { stopAll() }
            persist()
        }
    }

    /// Respect macOS Focus / Do Not Disturb. When true and Focus is on,
    /// only Thrawn is allowed to speak (priority agent). Everyone else is
    /// dropped with a flight-recorder log entry.
    @Published var respectFocus: Bool = true { didSet { persist() } }

    /// Quiet hours — closed range of hours (0–23). Announcements during
    /// this window are dropped. Nil means always-on.
    @Published var quietHoursStart: Int? = 22 { didSet { persist() } }
    @Published var quietHoursEnd: Int? = 7 { didSet { persist() } }

    /// Max simultaneously queued announcements. 4th+ drops oldest.
    @Published var maxQueueDepth: Int = 3 { didSet { persist() } }

    /// The agent currently speaking, for UI chrome. Nil when idle.
    @Published private(set) var currentlySpeakingAgentId: String?

    /// Snapshot of pending announcements (for the UI popover).
    @Published private(set) var pendingCount: Int = 0

    /// True while a streaming voice turn is open. The mic pipeline reads this
    /// to decide whether inbound speech is a barge-in rather than an echo.
    @Published private(set) var isStreamingTurn = false

    /// True whenever audio is actually leaving the speakers.
    var isSpeaking: Bool { synth.isSpeaking }

    // MARK: Private state

    private let synth = AVSpeechSynthesizer()
    private var queue: [Announcement] = []
    private weak var specStore: AgentSpecStore?

    private static let settingsPath = ThrawnPaths.appSupportDir
        .appendingPathComponent("voice-settings.json")

    // MARK: - Types

    enum AnnouncementKind: String, Codable {
        case open    // first line of a heartbeat — "R2 here. Building TASK-049."
        case close   // last line on completion — "R2 out. Build clean."
        case manual  // user-initiated ("play sample") or system messages
    }

    struct Announcement: Identifiable {
        let id = UUID()
        let agentId: String
        let kind: AnnouncementKind
        let text: String
        /// Chunks of a single streaming turn. They are exempt from the queue
        /// cap (dropping the middle of a sentence would garble the reply) and
        /// speak with no inter-utterance padding so the turn sounds like one
        /// continuous voice rather than a stack of announcements.
        var isStreamChunk: Bool = false
    }

    // MARK: - Init

    override init() {
        super.init()
        synth.delegate = self
        loadSettings()
    }

    /// Bind the spec store so we can resolve per-agent voice config.
    /// Also runs the voice-assignment migration: any spec whose current
    /// voiceIdentifier is nil or points at a voice that isn't installed
    /// on this machine gets auto-assigned from the preference list.
    func bind(specStore: AgentSpecStore) {
        self.specStore = specStore
        assignVoicesIfNeeded()
    }

    // MARK: - Per-agent voice preferences
    //
    // Each agent has an ordered list of AVSpeechSynthesisVoice
    // identifiers, best-first. On bind we walk the list and pick the
    // first one that resolves via AVSpeechSynthesisVoice(identifier:).
    // Rate and pitch tune the character. V2.0 ships with Thrawn as the
    // only active default voice assignment.
    //
    // If the user downloads new voices later, the migration will pick
    // them up on next launch only if the current assignment is invalid
    // — we don't clobber valid assignments so a future voice-picker UI
    // can override without fighting the auto-migration.

    private struct VoicePreference {
        let identifiers: [String]
        let rate: Float
        let pitch: Float
        let muted: Bool
        let forcePreferred: Bool
    }

    private static let voicePreferences: [String: VoicePreference] = [
        "thrawn": VoicePreference(
            identifiers: [
                "com.apple.voice.premium.en-GB.Malcolm",  // Jamie (Premium)
                "com.apple.voice.premium.en-GB.Serena",
                "com.apple.voice.enhanced.en-US.Tom",
            ],
            rate: 0.46, pitch: 0.96, muted: false, forcePreferred: false
        ),
    ]

    /// Walk the preference list for each agent, pick the first installed
    /// voice, and write the assignments to the spec store. Leaves specs
    /// with an already-valid identifier alone. Idempotent — safe to call
    /// on every bind.
    private func assignVoicesIfNeeded() {
        guard let store = specStore else { return }

        var updates: [String: AgentSpecStore.VoiceAssignment] = [:]
        var assignedCount = 0
        var skippedCount = 0

        for spec in store.specs {
            guard let pref = Self.voicePreferences[spec.id] else { continue }

            let picked = pref.identifiers.first { candidate in
                AVSpeechSynthesisVoice(identifier: candidate) != nil
            }
            let shouldForcePreferred = pref.forcePreferred
                && picked != nil
                && spec.voiceIdentifier != picked

            // If the current identifier already resolves to an installed
            // voice, leave it alone — respects any manual override from
            // a future voice-picker UI unless this agent has an explicit
            // canonical voice assignment.
            if let vid = spec.voiceIdentifier, !vid.isEmpty,
               AVSpeechSynthesisVoice(identifier: vid) != nil,
               !shouldForcePreferred {
                skippedCount += 1
                continue
            }

            updates[spec.id] = AgentSpecStore.VoiceAssignment(
                identifier: picked,
                rate: pref.rate,
                pitch: pref.pitch,
                muted: pref.muted
            )
            assignedCount += 1

            FlightRecorder.logEvent(
                category: "voice", action: "auto-assign",
                detail: "\(spec.id) → \(picked ?? "<muted/none>") @ rate=\(pref.rate) pitch=\(pref.pitch)"
            )
        }

        if !updates.isEmpty {
            store.applyVoiceUpdates(updates)
        }

        FlightRecorder.logEvent(
            category: "voice", action: "migration-complete",
            detail: "assigned=\(assignedCount) skipped=\(skippedCount)"
        )
    }

    // MARK: - Public API

    /// Enqueue an announcement from an agent. Returns true if accepted,
    /// false if dropped (mute / quiet hours / focus / per-agent mute).
    @discardableResult
    func announce(
        agentId: String,
        kind: AnnouncementKind,
        text: String
    ) -> Bool {
        // Master mute
        guard !muted else {
            FlightRecorder.logEvent(
                category: "voice", action: "dropped",
                detail: "muted: \(agentId) [\(kind.rawValue)]"
            )
            return false
        }

        // Quiet hours
        if inQuietHours() {
            FlightRecorder.logEvent(
                category: "voice", action: "dropped",
                detail: "quiet-hours: \(agentId) [\(kind.rawValue)]"
            )
            return false
        }

        // Per-agent mute on AgentSpec
        if let spec = specStore?.spec(id: agentId), spec.voiceMuted {
            FlightRecorder.logEvent(
                category: "voice", action: "dropped",
                detail: "agent-muted: \(agentId) [\(kind.rawValue)]"
            )
            return false
        }

        // Focus-aware: only Thrawn may speak during Focus, everyone else drops
        if respectFocus && isFocusActive() && agentId != "thrawn" {
            FlightRecorder.logEvent(
                category: "voice", action: "dropped",
                detail: "focus: \(agentId) [\(kind.rawValue)]"
            )
            return false
        }

        // Trim + normalize the text (one sentence, capped)
        let cleaned = Self.cleanAnnouncementText(text)
        guard !cleaned.isEmpty else { return false }

        // Enqueue; drop oldest if over cap. Stream chunks are never dropped —
        // cutting the middle out of a spoken reply is worse than a short wait.
        let item = Announcement(agentId: agentId, kind: kind, text: cleaned)
        queue.append(item)
        while queue.filter({ !$0.isStreamChunk }).count > maxQueueDepth,
              let dropIndex = queue.firstIndex(where: { !$0.isStreamChunk }) {
            let dropped = queue.remove(at: dropIndex)
            FlightRecorder.logEvent(
                category: "voice", action: "queue-drop",
                detail: "\(dropped.agentId): \(dropped.text.prefix(60))"
            )
        }
        pendingCount = queue.count

        FlightRecorder.logEvent(
            category: "voice", action: "enqueued",
            detail: "\(agentId) [\(kind.rawValue)]: \(cleaned.prefix(100))"
        )

        drain()
        return true
    }

    /// Fire a one-off sample in a specific agent's voice. Used by the
    /// "Play sample" button in the Agents console.
    func playSample(for agentId: String) {
        let name = specStore?.spec(id: agentId)?.name ?? agentId.capitalized
        let line = "\(name) here. Standing by for orders."
        announce(agentId: agentId, kind: .manual, text: line)
    }

    /// Speak an explicit user-requested voice-chat response. This bypasses
    /// quiet hours and Focus filtering because the user intentionally opened
    /// the mic, while still respecting the global mute switch.
    @discardableResult
    func speakInteractive(agentId: String, text: String) -> Bool {
        guard !muted else {
            FlightRecorder.logEvent(
                category: "voice", action: "dropped",
                detail: "muted interactive: \(agentId)"
            )
            return false
        }

        if let spec = specStore?.spec(id: agentId), spec.voiceMuted {
            FlightRecorder.logEvent(
                category: "voice", action: "dropped",
                detail: "agent-muted interactive: \(agentId)"
            )
            return false
        }

        let cleaned = Self.cleanInteractiveSpeechText(text)
        guard !cleaned.isEmpty else { return false }

        queue.append(Announcement(agentId: agentId, kind: .manual, text: cleaned))
        while queue.filter({ !$0.isStreamChunk }).count > maxQueueDepth,
              let dropIndex = queue.firstIndex(where: { !$0.isStreamChunk }) {
            queue.remove(at: dropIndex)
        }
        pendingCount = queue.count
        FlightRecorder.logEvent(
            category: "voice", action: "interactive-enqueued",
            detail: "\(agentId): \(cleaned.prefix(100))"
        )
        drain()
        return true
    }

    // MARK: - Streaming turns (Tier 1 latency)
    //
    // A conversational reply arrives as a token stream. Waiting for the full
    // response before speaking costs the entire generation time in silence.
    // Instead we buffer deltas and flush at natural boundaries, so the first
    // audio starts about as soon as the model has produced one clause.
    //
    // The first flush is deliberately eager (clause-level) because
    // time-to-first-audio is what a listener perceives as latency. Later
    // flushes wait for sentence terminators so prosody stays natural.

    private var streamBuffer = ""
    private var streamAgentId: String?
    private var streamChunkIndex = 0

    /// Open a streaming turn. Any in-flight speech is cleared first.
    func beginStreamingTurn(agentId: String) {
        stopAll()
        streamBuffer = ""
        streamAgentId = agentId
        streamChunkIndex = 0
        isStreamingTurn = true
        FlightRecorder.logEvent(category: "voice", action: "stream-begin", detail: agentId)
    }

    /// Feed a token delta. Speaks complete clauses/sentences as they form.
    func appendStreamingDelta(_ delta: String) {
        guard isStreamingTurn, !muted else { return }
        streamBuffer += delta
        while let boundary = nextFlushBoundary(in: streamBuffer) {
            let chunk = String(streamBuffer[..<boundary])
            streamBuffer = String(streamBuffer[boundary...])
            speakChunk(chunk)
        }
    }

    /// Close the turn, flushing whatever is left in the buffer.
    func endStreamingTurn() {
        guard isStreamingTurn else { return }
        let tail = streamBuffer
        streamBuffer = ""
        isStreamingTurn = false
        if !tail.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            speakChunk(tail)
        }
        FlightRecorder.logEvent(
            category: "voice", action: "stream-end",
            detail: "\(streamAgentId ?? "?") chunks=\(streamChunkIndex)"
        )
        streamAgentId = nil
    }

    /// Cut speech instantly because the user started talking over it.
    func interruptForBargeIn() {
        guard synth.isSpeaking || !queue.isEmpty || isStreamingTurn else { return }
        streamBuffer = ""
        isStreamingTurn = false
        streamAgentId = nil
        stopAll()
        FlightRecorder.logEvent(category: "voice", action: "barge-in", detail: "user interrupted playback")
    }

    /// Find where the buffer can be cut for speech, or nil to keep buffering.
    /// Returns an index *after* the boundary character.
    private func nextFlushBoundary(in text: String) -> String.Index? {
        // Eager on the opening clause — first audio dominates perceived latency.
        let isFirst = streamChunkIndex == 0
        let minLength = isFirst ? 16 : 40
        let hardLength = isFirst ? 90 : 200
        guard text.count >= minLength else { return nil }

        let terminators: Set<Character> = isFirst
            ? [".", "!", "?", "\n", ",", ";", ":"]
            : [".", "!", "?", "\n"]

        var lastValid: String.Index?
        var idx = text.startIndex
        var offset = 0
        while idx < text.endIndex {
            let ch = text[idx]
            let next = text.index(after: idx)
            if terminators.contains(ch), offset + 1 >= minLength {
                // A period inside a decimal or an abbreviation isn't a boundary.
                let followedByDigit = next < text.endIndex && text[next].isNumber
                if !(ch == "." && followedByDigit) {
                    lastValid = next
                }
            }
            idx = next
            offset += 1
        }
        if let lastValid { return lastValid }

        // No punctuation but the buffer is long — cut at the last space so we
        // never sit on a wall of text waiting for a period that isn't coming.
        if text.count >= hardLength,
           let space = text.lastIndex(of: " ") {
            return text.index(after: space)
        }
        return nil
    }

    private func speakChunk(_ raw: String) {
        guard let agentId = streamAgentId else { return }
        let cleaned = Self.cleanInteractiveSpeechText(raw)
        guard !cleaned.isEmpty else { return }
        queue.append(Announcement(agentId: agentId, kind: .manual, text: cleaned, isStreamChunk: true))
        pendingCount = queue.count
        streamChunkIndex += 1
        drain()
    }

    /// Stop everything immediately and clear the queue.
    func stopAll() {
        synth.stopSpeaking(at: .immediate)
        queue.removeAll()
        pendingCount = 0
        currentlySpeakingAgentId = nil
    }

    // MARK: - File rendering (SOD/EOD briefings)
    //
    // Render an utterance to a .caf audio file on disk using the agent's
    // assigned voice/rate/pitch. Used by BriefingService so SOD/EOD
    // briefings get saved as real audio files you can replay later.
    //
    // Uses a dedicated AVSpeechSynthesizer per call so it doesn't
    // stomp on the live-announcement synth.

    private final class RenderState {
        var audioFile: AVAudioFile?
        var resumed = false
        var wroteAnything = false
    }

    /// Render `text` to `url` (.caf) in the agent's voice. Returns true
    /// on success, false if the synth refused (some Siri-tier voices
    /// can't be captured) or the file write failed. Never throws.
    func renderToFile(
        agentId: String,
        text: String,
        url: URL
    ) async -> Bool {
        // Clean + cap like a live announcement so we don't ship 10-minute files
        let cleaned = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !cleaned.isEmpty else { return false }

        // Make sure the parent dir exists
        try? FileManager.default.createDirectory(
            at: url.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )

        let utterance = AVSpeechUtterance(string: cleaned)
        configureUtterance(utterance, forAgentId: agentId)
        // Tighter bumpers for file renders — no need for live-queue pauses.
        utterance.preUtteranceDelay = 0.0
        utterance.postUtteranceDelay = 0.0

        // Dedicated synth for the render so we don't interleave with live speech.
        let writer = AVSpeechSynthesizer()

        return await withCheckedContinuation { (cont: CheckedContinuation<Bool, Never>) in
            let state = RenderState()

            // Safety timeout: if the callback never fires completion, don't hang forever.
            let timeoutTask = Task { [weak writer] in
                try? await Task.sleep(nanoseconds: 60_000_000_000) // 60s cap
                if !state.resumed {
                    state.resumed = true
                    writer?.stopSpeaking(at: .immediate)
                    FlightRecorder.logEvent(
                        category: "voice", action: "render-timeout",
                        detail: "\(agentId): \(cleaned.prefix(60))"
                    )
                    cont.resume(returning: false)
                }
            }

            writer.write(utterance) { buffer in
                guard !state.resumed else { return }

                guard let pcm = buffer as? AVAudioPCMBuffer else { return }

                // 0-length buffer is the terminator per AVSpeechSynthesizer docs.
                if pcm.frameLength == 0 {
                    state.resumed = true
                    timeoutTask.cancel()
                    let ok = state.wroteAnything && state.audioFile != nil
                    if !ok {
                        FlightRecorder.logEvent(
                            category: "voice", action: "render-empty",
                            detail: "\(agentId): synth produced no audio"
                        )
                    }
                    cont.resume(returning: ok)
                    return
                }

                // Lazy-create the audio file using the format of the first real buffer.
                if state.audioFile == nil {
                    do {
                        state.audioFile = try AVAudioFile(
                            forWriting: url,
                            settings: pcm.format.settings,
                            commonFormat: pcm.format.commonFormat,
                            interleaved: pcm.format.isInterleaved
                        )
                    } catch {
                        state.resumed = true
                        timeoutTask.cancel()
                        FlightRecorder.logEvent(
                            category: "voice", action: "render-failed",
                            detail: "\(agentId): file-create \(error.localizedDescription)"
                        )
                        cont.resume(returning: false)
                        return
                    }
                }

                do {
                    try state.audioFile?.write(from: pcm)
                    state.wroteAnything = true
                } catch {
                    // Keep going; log once.
                    FlightRecorder.logEvent(
                        category: "voice", action: "render-write-err",
                        detail: "\(agentId): \(error.localizedDescription)"
                    )
                }
            }
        }
    }

    /// Configure an AVSpeechUtterance with the agent's voice/rate/pitch.
    /// Shared by the live queue drain and the file renderer.
    func configureUtterance(_ utterance: AVSpeechUtterance, forAgentId agentId: String) {
        if let spec = specStore?.spec(id: agentId) {
            if let vid = spec.voiceIdentifier,
               let voice = AVSpeechSynthesisVoice(identifier: vid) {
                utterance.voice = voice
            } else {
                utterance.voice = AVSpeechSynthesisVoice(language: "en-US")
            }
            utterance.rate = spec.speechRate
            utterance.pitchMultiplier = spec.speechPitch
        } else {
            utterance.voice = AVSpeechSynthesisVoice(language: "en-US")
            utterance.rate = 0.50
            utterance.pitchMultiplier = 1.0
        }
    }

    // MARK: - Queue drain

    private func drain() {
        // If already speaking, delegate callback will re-drain when done.
        guard !synth.isSpeaking else { return }
        guard !queue.isEmpty else {
            currentlySpeakingAgentId = nil
            return
        }

        let next = queue.removeFirst()
        pendingCount = queue.count
        currentlySpeakingAgentId = next.agentId

        let utterance = AVSpeechUtterance(string: next.text)
        configureUtterance(utterance, forAgentId: next.agentId)

        if next.isStreamChunk {
            // One continuous turn — any padding here reads as a stutter.
            utterance.preUtteranceDelay = 0
            utterance.postUtteranceDelay = 0
        } else {
            // Small pre-pause so queued announcements don't slam into each other
            utterance.preUtteranceDelay = 0.15
            utterance.postUtteranceDelay = 0.10
        }

        synth.speak(utterance)
    }

    // MARK: - Text cleaning

    /// Extract the first sentence from a potentially multi-line blob,
    /// strip markdown, cap length. Used for announcements peeled from
    /// LLM responses.
    static func cleanAnnouncementText(_ raw: String) -> String {
        var s = raw.trimmingCharacters(in: .whitespacesAndNewlines)

        // Take first line
        if let newline = s.firstIndex(of: "\n") {
            s = String(s[..<newline])
        }

        // Strip basic markdown (headers, bold, italic, inline code, link text)
        s = s.replacingOccurrences(of: #"^\s*#+\s*"#, with: "", options: .regularExpression)
        s = s.replacingOccurrences(of: #"\*\*(.+?)\*\*"#, with: "$1", options: .regularExpression)
        s = s.replacingOccurrences(of: #"`([^`]+)`"#, with: "$1", options: .regularExpression)
        s = s.replacingOccurrences(of: #"\[([^\]]+)\]\([^\)]+\)"#, with: "$1", options: .regularExpression)

        // Cap total length — we don't want a wall-of-text announcement
        if s.count > 220 {
            s = String(s.prefix(220)).trimmingCharacters(in: .whitespaces) + "…"
        }
        return s.trimmingCharacters(in: .whitespaces)
    }

    static func cleanInteractiveSpeechText(_ raw: String) -> String {
        var s = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        s = s.replacingOccurrences(of: #"```[\s\S]*?```"#, with: "", options: .regularExpression)
        s = s.replacingOccurrences(of: #"^\s*#+\s*"#, with: "", options: .regularExpression)
        s = s.replacingOccurrences(of: #"\*\*(.+?)\*\*"#, with: "$1", options: .regularExpression)
        s = s.replacingOccurrences(of: #"`([^`]+)`"#, with: "$1", options: .regularExpression)
        s = s.replacingOccurrences(of: #"\[([^\]]+)\]\([^\)]+\)"#, with: "$1", options: .regularExpression)
        s = s.components(separatedBy: "\n")
            .map { $0.trimmingCharacters(in: .whitespaces) }
            .filter { !$0.isEmpty }
            .joined(separator: " ")
        if s.count > 900 {
            s = String(s.prefix(900)).trimmingCharacters(in: .whitespaces) + "…"
        }
        return s
    }

    // MARK: - Focus / Quiet hours detection

    /// Quiet hours check — returns true if the current hour is inside
    /// the [start, end) window. Handles overnight wraps (e.g. 22..7).
    private func inQuietHours() -> Bool {
        guard let start = quietHoursStart, let end = quietHoursEnd,
              (0...23).contains(start), (0...23).contains(end),
              start != end else { return false }
        let hour = Calendar.current.component(.hour, from: Date())
        if start < end {
            return hour >= start && hour < end
        } else {
            // Overnight wrap: e.g. 22..7 means 22,23,0,1,..,6
            return hour >= start || hour < end
        }
    }

    /// Best-effort Focus / Do Not Disturb check. macOS exposes this via
    /// NSUserNotificationCenter.default.doNotDisturb on older systems, and
    /// via UserNotifications on newer. For simplicity we check the
    /// preference plist directly — it's the most reliable cross-version path.
    private func isFocusActive() -> Bool {
        // Check the Focus assertion file. Apple writes the active focus
        // state to ~/Library/DoNotDisturb/DB/Assertions.json on modern macOS.
        let fm = FileManager.default
        let home = fm.homeDirectoryForCurrentUser
        let focusFile = home
            .appendingPathComponent("Library/DoNotDisturb/DB/Assertions.json")
        guard let data = try? Data(contentsOf: focusFile),
              let obj = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let records = obj["data"] as? [[String: Any]] else {
            return false
        }
        // Any non-empty storeAssertionRecords means a focus is active
        for r in records {
            if let arr = r["storeAssertionRecords"] as? [[String: Any]], !arr.isEmpty {
                return true
            }
        }
        return false
    }

    // MARK: - Persistence

    private struct PersistedSettings: Codable {
        var muted: Bool
        var respectFocus: Bool
        var quietHoursStart: Int?
        var quietHoursEnd: Int?
        var maxQueueDepth: Int
    }

    private func persist() {
        let s = PersistedSettings(
            muted: muted,
            respectFocus: respectFocus,
            quietHoursStart: quietHoursStart,
            quietHoursEnd: quietHoursEnd,
            maxQueueDepth: maxQueueDepth
        )
        let data: Data
        do {
            data = try JSONEncoder().encode(s)
        } catch {
            FlightRecorder.logError(
                source: "voice:saveSettings",
                message: "Encode failed: \(error.localizedDescription)"
            )
            return
        }
        do {
            try data.write(to: Self.settingsPath, options: .atomic)
        } catch {
            FlightRecorder.logError(
                source: "voice:saveSettings",
                message: "Write \(Self.settingsPath.lastPathComponent) failed: \(error.localizedDescription)"
            )
        }
    }

    private func loadSettings() {
        guard let data = try? Data(contentsOf: Self.settingsPath),
              let s = try? JSONDecoder().decode(PersistedSettings.self, from: data) else {
            return
        }
        // Set directly to avoid didSet re-persisting during init
        self.muted = s.muted
        self.respectFocus = s.respectFocus
        self.quietHoursStart = s.quietHoursStart
        self.quietHoursEnd = s.quietHoursEnd
        self.maxQueueDepth = max(1, s.maxQueueDepth)
    }
}

// MARK: - AVSpeechSynthesizerDelegate

extension VoiceService: AVSpeechSynthesizerDelegate {
    nonisolated func speechSynthesizer(
        _ synthesizer: AVSpeechSynthesizer,
        didFinish utterance: AVSpeechUtterance
    ) {
        Task { @MainActor in
            self.currentlySpeakingAgentId = nil
            self.drain()
        }
    }

    nonisolated func speechSynthesizer(
        _ synthesizer: AVSpeechSynthesizer,
        didCancel utterance: AVSpeechUtterance
    ) {
        Task { @MainActor in
            self.currentlySpeakingAgentId = nil
            self.drain()
        }
    }
}
