import Foundation
import AVFoundation
import SwiftUI
import Combine

// MARK: - Voice Service
//
// The spoken voice layer for the agent squad. Every agent announces
// what they're starting (open) and what they accomplished (close) at
// each heartbeat. Announcements are generated by the LLM as the first
// and last line of its response — AgentScheduler peels them off and
// routes them through this service.
//
// Design rules (from the architecture pass):
//   • One utterance speaks at a time. Concurrent announcements queue.
//   • Queue depth capped (default 3). Fourth announcement drops the oldest
//     — agents shouldn't stack up more than a few seconds of backlog.
//   • Global mute kills the queue instantly.
//   • Per-agent mute (on AgentSpec.voiceMuted) is respected at enqueue time.
//   • Quiet hours (default 22:00–07:00) silently drop announcements but
//     still log them to the flight recorder.
//   • Siri-2-ready: everything goes through AVSpeechSynthesizer, so when
//     Apple adds a .neural quality tier or new identifiers, flipping the
//     voiceIdentifier on an AgentSpec is the only change needed.
//
// Thread safety: @MainActor — all state mutations happen on the main
// thread. AVSpeechSynthesizer's delegate callbacks are marshaled back
// onto the main actor before touching state.

@MainActor
final class VoiceService: NSObject, ObservableObject {
    // MARK: Published state (UI bindings)

    /// Master mute. When true, all announcements are dropped on enqueue.
    @Published var muted: Bool = false {
        didSet {
            if muted { stopAll() }
            persist()
        }
    }

    /// Respect macOS Focus / Do Not Disturb. When true and Focus is on,
    /// only Thrawn is allowed to speak (priority agent). Everyone else is
    /// dropped with a flight-recorder log entry.
    @Published var respectFocus: Bool = true { didSet { persist() } }

    /// Quiet hours — closed range of hours (0–23). Announcements during
    /// this window are dropped. Nil means always-on.
    @Published var quietHoursStart: Int? = 22 { didSet { persist() } }
    @Published var quietHoursEnd: Int? = 7 { didSet { persist() } }

    /// Max simultaneously queued announcements. 4th+ drops oldest.
    @Published var maxQueueDepth: Int = 3 { didSet { persist() } }

    /// The agent currently speaking, for UI chrome. Nil when idle.
    @Published private(set) var currentlySpeakingAgentId: String?

    /// Snapshot of pending announcements (for the UI popover).
    @Published private(set) var pendingCount: Int = 0

    // MARK: Private state

    private let synth = AVSpeechSynthesizer()
    private var queue: [Announcement] = []
    private weak var specStore: AgentSpecStore?

    private static let settingsPath = ThrawnPaths.appSupportDir
        .appendingPathComponent("voice-settings.json")

    // MARK: - Types

    enum AnnouncementKind: String, Codable {
        case open    // first line of a heartbeat — "R2 here. Building TASK-049."
        case close   // last line on completion — "R2 out. Build clean."
        case manual  // user-initiated ("play sample") or system messages
    }

    struct Announcement: Identifiable {
        let id = UUID()
        let agentId: String
        let kind: AnnouncementKind
        let text: String
    }

    // MARK: - Init

    override init() {
        super.init()
        synth.delegate = self
        loadSettings()
    }

    /// Bind the spec store so we can resolve per-agent voice config.
    /// Also runs the voice-assignment migration: any spec whose current
    /// voiceIdentifier is nil or points at a voice that isn't installed
    /// on this machine gets auto-assigned from the preference list.
    func bind(specStore: AgentSpecStore) {
        self.specStore = specStore
        assignVoicesIfNeeded()
    }

    // MARK: - Per-agent voice preferences
    //
    // Each agent has an ordered list of AVSpeechSynthesisVoice
    // identifiers, best-first. On bind we walk the list and pick the
    // first one that resolves via AVSpeechSynthesisVoice(identifier:).
    // Rate and pitch tune the character: Boba is slow+low, Bart is fast
    // +bright, Thrawn is calm and slightly lower, C-3PO is slightly
    // faster and brighter (fussy protocol droid).
    //
    // If the user downloads new voices later, the migration will pick
    // them up on next launch only if the current assignment is invalid
    // — we don't clobber valid assignments so a future voice-picker UI
    // can override without fighting the auto-migration.

    private struct VoicePreference {
        let identifiers: [String]
        let rate: Float
        let pitch: Float
        let muted: Bool
    }

    private static let voicePreferences: [String: VoicePreference] = [
        "thrawn": VoicePreference(
            identifiers: [
                "com.apple.voice.premium.en-GB.Malcolm",  // Jamie (Premium)
                "com.apple.voice.premium.en-GB.Serena",
                "com.apple.voice.enhanced.en-US.Tom",
            ],
            rate: 0.46, pitch: 0.96, muted: false
        ),
        "quigon": VoicePreference(
            identifiers: [
                "com.apple.voice.premium.en-AU.Lee",      // Lee (Premium AU)
                "com.apple.voice.premium.en-AU.Karen",
                "com.apple.voice.enhanced.en-US.Evan",
            ],
            rate: 0.47, pitch: 1.00, muted: false
        ),
        "lando": VoicePreference(
            identifiers: [
                "com.apple.voice.enhanced.en-US.Evan",    // Evan (Enhanced)
                "com.apple.voice.enhanced.en-US.Nathan",
                "com.apple.voice.premium.en-US.Zoe",
            ],
            rate: 0.50, pitch: 1.00, muted: false
        ),
        "boba": VoicePreference(
            identifiers: [
                "com.apple.voice.enhanced.en-US.Tom",     // Tom (Enhanced)
                "com.apple.voice.enhanced.en-US.Nathan",
            ],
            rate: 0.44, pitch: 0.90, muted: false
        ),
        "bart": VoicePreference(
            identifiers: [
                "com.apple.voice.enhanced.en-US.Nathan",  // Nathan (Enhanced)
                "com.apple.voice.enhanced.en-US.Evan",
            ],
            rate: 0.54, pitch: 1.08, muted: false
        ),
        "c3po": VoicePreference(
            identifiers: [
                "com.apple.voice.compact.en-GB.Daniel",   // Daniel (compact — no enhanced exists)
                "com.apple.voice.premium.en-GB.Serena",
            ],
            rate: 0.52, pitch: 1.05, muted: false
        ),
        "r2d2": VoicePreference(
            identifiers: [],                              // SFX bank planned — no TTS voice
            rate: 0.50, pitch: 1.00, muted: true
        ),
        "hunter": VoicePreference(
            identifiers: [
                "com.apple.voice.premium.en-US.Ava",      // Ava (Premium) — sharp, direct
                "com.apple.voice.enhanced.en-US.Ava",
                "com.apple.voice.enhanced.en-US.Allison",
            ],
            rate: 0.50, pitch: 1.00, muted: false
        ),
        "alborland": VoicePreference(
            identifiers: [
                "com.apple.voice.enhanced.en-US.Fred",     // Fred (Enhanced) — flat, monotone
                "com.apple.voice.enhanced.en-US.Tom",
                "com.apple.voice.compact.en-US.Fred",
            ],
            rate: 0.46, pitch: 0.92, muted: false
        ),
    ]

    /// Walk the preference list for each agent, pick the first installed
    /// voice, and write the assignments to the spec store. Leaves specs
    /// with an already-valid identifier alone. Idempotent — safe to call
    /// on every bind.
    private func assignVoicesIfNeeded() {
        guard let store = specStore else { return }

        var updates: [String: AgentSpecStore.VoiceAssignment] = [:]
        var assignedCount = 0
        var skippedCount = 0

        for spec in store.specs {
            guard let pref = Self.voicePreferences[spec.id] else { continue }

            // If the current identifier already resolves to an installed
            // voice, leave it alone — respects any manual override from
            // a future voice-picker UI.
            if let vid = spec.voiceIdentifier, !vid.isEmpty,
               AVSpeechSynthesisVoice(identifier: vid) != nil {
                skippedCount += 1
                continue
            }

            // Pick the first installed candidate.
            var picked: String? = nil
            for candidate in pref.identifiers {
                if AVSpeechSynthesisVoice(identifier: candidate) != nil {
                    picked = candidate
                    break
                }
            }

            updates[spec.id] = AgentSpecStore.VoiceAssignment(
                identifier: picked,
                rate: pref.rate,
                pitch: pref.pitch,
                muted: pref.muted
            )
            assignedCount += 1

            FlightRecorder.logEvent(
                category: "voice", action: "auto-assign",
                detail: "\(spec.id) → \(picked ?? "<muted/none>") @ rate=\(pref.rate) pitch=\(pref.pitch)"
            )
        }

        if !updates.isEmpty {
            store.applyVoiceUpdates(updates)
        }

        FlightRecorder.logEvent(
            category: "voice", action: "migration-complete",
            detail: "assigned=\(assignedCount) skipped=\(skippedCount)"
        )
    }

    // MARK: - Public API

    /// Enqueue an announcement from an agent. Returns true if accepted,
    /// false if dropped (mute / quiet hours / focus / per-agent mute).
    @discardableResult
    func announce(
        agentId: String,
        kind: AnnouncementKind,
        text: String
    ) -> Bool {
        // Master mute
        guard !muted else {
            FlightRecorder.logEvent(
                category: "voice", action: "dropped",
                detail: "muted: \(agentId) [\(kind.rawValue)]"
            )
            return false
        }

        // Quiet hours
        if inQuietHours() {
            FlightRecorder.logEvent(
                category: "voice", action: "dropped",
                detail: "quiet-hours: \(agentId) [\(kind.rawValue)]"
            )
            return false
        }

        // Per-agent mute on AgentSpec
        if let spec = specStore?.spec(id: agentId), spec.voiceMuted {
            FlightRecorder.logEvent(
                category: "voice", action: "dropped",
                detail: "agent-muted: \(agentId) [\(kind.rawValue)]"
            )
            return false
        }

        // Focus-aware: only Thrawn may speak during Focus, everyone else drops
        if respectFocus && isFocusActive() && agentId != "thrawn" {
            FlightRecorder.logEvent(
                category: "voice", action: "dropped",
                detail: "focus: \(agentId) [\(kind.rawValue)]"
            )
            return false
        }

        // Trim + normalize the text (one sentence, capped)
        let cleaned = Self.cleanAnnouncementText(text)
        guard !cleaned.isEmpty else { return false }

        // Enqueue; drop oldest if over cap
        let item = Announcement(agentId: agentId, kind: kind, text: cleaned)
        queue.append(item)
        while queue.count > maxQueueDepth {
            let dropped = queue.removeFirst()
            FlightRecorder.logEvent(
                category: "voice", action: "queue-drop",
                detail: "\(dropped.agentId): \(dropped.text.prefix(60))"
            )
        }
        pendingCount = queue.count

        FlightRecorder.logEvent(
            category: "voice", action: "enqueued",
            detail: "\(agentId) [\(kind.rawValue)]: \(cleaned.prefix(100))"
        )

        drain()
        return true
    }

    /// Fire a one-off sample in a specific agent's voice. Used by the
    /// "Play sample" button in the Agents console.
    func playSample(for agentId: String) {
        let name = specStore?.spec(id: agentId)?.name ?? agentId.capitalized
        let line = "\(name) here. Standing by for orders."
        announce(agentId: agentId, kind: .manual, text: line)
    }

    /// Stop everything immediately and clear the queue.
    func stopAll() {
        synth.stopSpeaking(at: .immediate)
        queue.removeAll()
        pendingCount = 0
        currentlySpeakingAgentId = nil
    }

    // MARK: - File rendering (SOD/EOD briefings)
    //
    // Render an utterance to a .caf audio file on disk using the agent's
    // assigned voice/rate/pitch. Used by BriefingService so SOD/EOD
    // briefings get saved as real audio files you can replay later.
    //
    // Uses a dedicated AVSpeechSynthesizer per call so it doesn't
    // stomp on the live-announcement synth.

    private final class RenderState {
        var audioFile: AVAudioFile?
        var resumed = false
        var wroteAnything = false
    }

    /// Render `text` to `url` (.caf) in the agent's voice. Returns true
    /// on success, false if the synth refused (some Siri-tier voices
    /// can't be captured) or the file write failed. Never throws.
    func renderToFile(
        agentId: String,
        text: String,
        url: URL
    ) async -> Bool {
        // Clean + cap like a live announcement so we don't ship 10-minute files
        let cleaned = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !cleaned.isEmpty else { return false }

        // Make sure the parent dir exists
        try? FileManager.default.createDirectory(
            at: url.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )

        let utterance = AVSpeechUtterance(string: cleaned)
        configureUtterance(utterance, forAgentId: agentId)
        // Tighter bumpers for file renders — no need for live-queue pauses.
        utterance.preUtteranceDelay = 0.0
        utterance.postUtteranceDelay = 0.0

        // Dedicated synth for the render so we don't interleave with live speech.
        let writer = AVSpeechSynthesizer()

        return await withCheckedContinuation { (cont: CheckedContinuation<Bool, Never>) in
            let state = RenderState()

            // Safety timeout: if the callback never fires completion, don't hang forever.
            let timeoutTask = Task { [weak writer] in
                try? await Task.sleep(nanoseconds: 60_000_000_000) // 60s cap
                if !state.resumed {
                    state.resumed = true
                    writer?.stopSpeaking(at: .immediate)
                    FlightRecorder.logEvent(
                        category: "voice", action: "render-timeout",
                        detail: "\(agentId): \(cleaned.prefix(60))"
                    )
                    cont.resume(returning: false)
                }
            }

            writer.write(utterance) { buffer in
                guard !state.resumed else { return }

                guard let pcm = buffer as? AVAudioPCMBuffer else { return }

                // 0-length buffer is the terminator per AVSpeechSynthesizer docs.
                if pcm.frameLength == 0 {
                    state.resumed = true
                    timeoutTask.cancel()
                    let ok = state.wroteAnything && state.audioFile != nil
                    if !ok {
                        FlightRecorder.logEvent(
                            category: "voice", action: "render-empty",
                            detail: "\(agentId): synth produced no audio"
                        )
                    }
                    cont.resume(returning: ok)
                    return
                }

                // Lazy-create the audio file using the format of the first real buffer.
                if state.audioFile == nil {
                    do {
                        state.audioFile = try AVAudioFile(
                            forWriting: url,
                            settings: pcm.format.settings,
                            commonFormat: pcm.format.commonFormat,
                            interleaved: pcm.format.isInterleaved
                        )
                    } catch {
                        state.resumed = true
                        timeoutTask.cancel()
                        FlightRecorder.logEvent(
                            category: "voice", action: "render-failed",
                            detail: "\(agentId): file-create \(error.localizedDescription)"
                        )
                        cont.resume(returning: false)
                        return
                    }
                }

                do {
                    try state.audioFile?.write(from: pcm)
                    state.wroteAnything = true
                } catch {
                    // Keep going; log once.
                    FlightRecorder.logEvent(
                        category: "voice", action: "render-write-err",
                        detail: "\(agentId): \(error.localizedDescription)"
                    )
                }
            }
        }
    }

    /// Configure an AVSpeechUtterance with the agent's voice/rate/pitch.
    /// Shared by the live queue drain and the file renderer.
    func configureUtterance(_ utterance: AVSpeechUtterance, forAgentId agentId: String) {
        if let spec = specStore?.spec(id: agentId) {
            if let vid = spec.voiceIdentifier,
               let voice = AVSpeechSynthesisVoice(identifier: vid) {
                utterance.voice = voice
            } else {
                utterance.voice = AVSpeechSynthesisVoice(language: "en-US")
            }
            utterance.rate = spec.speechRate
            utterance.pitchMultiplier = spec.speechPitch
        } else {
            utterance.voice = AVSpeechSynthesisVoice(language: "en-US")
            utterance.rate = 0.50
            utterance.pitchMultiplier = 1.0
        }
    }

    // MARK: - Queue drain

    private func drain() {
        // If already speaking, delegate callback will re-drain when done.
        guard !synth.isSpeaking else { return }
        guard !queue.isEmpty else {
            currentlySpeakingAgentId = nil
            return
        }

        let next = queue.removeFirst()
        pendingCount = queue.count
        currentlySpeakingAgentId = next.agentId

        let utterance = AVSpeechUtterance(string: next.text)
        configureUtterance(utterance, forAgentId: next.agentId)

        // Small pre-pause so queued announcements don't slam into each other
        utterance.preUtteranceDelay = 0.15
        utterance.postUtteranceDelay = 0.10

        synth.speak(utterance)
    }

    // MARK: - Text cleaning

    /// Extract the first sentence from a potentially multi-line blob,
    /// strip markdown, cap length. Used for announcements peeled from
    /// LLM responses.
    static func cleanAnnouncementText(_ raw: String) -> String {
        var s = raw.trimmingCharacters(in: .whitespacesAndNewlines)

        // Take first line
        if let newline = s.firstIndex(of: "\n") {
            s = String(s[..<newline])
        }

        // Strip basic markdown (headers, bold, italic, inline code, link text)
        s = s.replacingOccurrences(of: #"^\s*#+\s*"#, with: "", options: .regularExpression)
        s = s.replacingOccurrences(of: #"\*\*(.+?)\*\*"#, with: "$1", options: .regularExpression)
        s = s.replacingOccurrences(of: #"`([^`]+)`"#, with: "$1", options: .regularExpression)
        s = s.replacingOccurrences(of: #"\[([^\]]+)\]\([^\)]+\)"#, with: "$1", options: .regularExpression)

        // Cap total length — we don't want a wall-of-text announcement
        if s.count > 220 {
            s = String(s.prefix(220)).trimmingCharacters(in: .whitespaces) + "…"
        }
        return s.trimmingCharacters(in: .whitespaces)
    }

    // MARK: - Focus / Quiet hours detection

    /// Quiet hours check — returns true if the current hour is inside
    /// the [start, end) window. Handles overnight wraps (e.g. 22..7).
    private func inQuietHours() -> Bool {
        guard let start = quietHoursStart, let end = quietHoursEnd,
              (0...23).contains(start), (0...23).contains(end),
              start != end else { return false }
        let hour = Calendar.current.component(.hour, from: Date())
        if start < end {
            return hour >= start && hour < end
        } else {
            // Overnight wrap: e.g. 22..7 means 22,23,0,1,..,6
            return hour >= start || hour < end
        }
    }

    /// Best-effort Focus / Do Not Disturb check. macOS exposes this via
    /// NSUserNotificationCenter.default.doNotDisturb on older systems, and
    /// via UserNotifications on newer. For simplicity we check the
    /// preference plist directly — it's the most reliable cross-version path.
    private func isFocusActive() -> Bool {
        // Check the Focus assertion file. Apple writes the active focus
        // state to ~/Library/DoNotDisturb/DB/Assertions.json on modern macOS.
        let fm = FileManager.default
        let home = fm.homeDirectoryForCurrentUser
        let focusFile = home
            .appendingPathComponent("Library/DoNotDisturb/DB/Assertions.json")
        guard let data = try? Data(contentsOf: focusFile),
              let obj = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let records = obj["data"] as? [[String: Any]] else {
            return false
        }
        // Any non-empty storeAssertionRecords means a focus is active
        for r in records {
            if let arr = r["storeAssertionRecords"] as? [[String: Any]], !arr.isEmpty {
                return true
            }
        }
        return false
    }

    // MARK: - Persistence

    private struct PersistedSettings: Codable {
        var muted: Bool
        var respectFocus: Bool
        var quietHoursStart: Int?
        var quietHoursEnd: Int?
        var maxQueueDepth: Int
    }

    private func persist() {
        let s = PersistedSettings(
            muted: muted,
            respectFocus: respectFocus,
            quietHoursStart: quietHoursStart,
            quietHoursEnd: quietHoursEnd,
            maxQueueDepth: maxQueueDepth
        )
        if let data = try? JSONEncoder().encode(s) {
            try? data.write(to: Self.settingsPath, options: .atomic)
        }
    }

    private func loadSettings() {
        guard let data = try? Data(contentsOf: Self.settingsPath),
              let s = try? JSONDecoder().decode(PersistedSettings.self, from: data) else {
            return
        }
        // Set directly to avoid didSet re-persisting during init
        self.muted = s.muted
        self.respectFocus = s.respectFocus
        self.quietHoursStart = s.quietHoursStart
        self.quietHoursEnd = s.quietHoursEnd
        self.maxQueueDepth = max(1, s.maxQueueDepth)
    }
}

// MARK: - AVSpeechSynthesizerDelegate

extension VoiceService: AVSpeechSynthesizerDelegate {
    nonisolated func speechSynthesizer(
        _ synthesizer: AVSpeechSynthesizer,
        didFinish utterance: AVSpeechUtterance
    ) {
        Task { @MainActor in
            self.currentlySpeakingAgentId = nil
            self.drain()
        }
    }

    nonisolated func speechSynthesizer(
        _ synthesizer: AVSpeechSynthesizer,
        didCancel utterance: AVSpeechUtterance
    ) {
        Task { @MainActor in
            self.currentlySpeakingAgentId = nil
            self.drain()
        }
    }
}
